repos:
- repo: local
  hooks:
  - id: run-tests
    name: Run Tests
    entry: ./tests/runtests
    language: script
    pass_filenames: false
    files: ''
    always_run: true
    pass_filenames: false
    stages:
    - commit
- repo: https://github.com/psf/black
  rev: 23.3.0  # Use the specific version of Black you want to run
  hooks:
  - id: black
    entry: black pyk
    language: python
    always_run: true
    additional_dependencies: [black]
    files: ^pyk$
    pass_filenames: false
